### ISSUE TITLE
Re: running the code on local server + effectiveness of Mujoco simulation

### ISSUE THREAD

**Issue by weijiafeng** [avisingh599/reward-learning-rl#10]
Hi Avi,

While I am still tackling various issues with installation, just want to raise two questions that've been concerning me:

1. If I want to use GPU on a local server to run the code, do I just simply run the example codes on the server? any other installations that I need to do?

2. Regarding the effective of Mujoco simulation - as I am new in this field, just wondering:

 1) What is the pros and cos of doing simulation on Mujoco+softlearning vs on real robotic arms? Is it that simulation can speed up the learning process hence is used before experimenting on real robots?

2) Are there big differences on the results obtained from simulations vs the result on real robots provided the same set of policies/strategies? 

Many thanks for your reply!

**Comment by avisingh599** [comment]
1. Yes, just running the example code on local server will work, you don't have to do anything else. 
2. 1. Yes, simulation is good for fast prototyping, and for conducting experiments with many different random seeds to see the variance between runs. 
2. 2. No, there aren't any big differences in the final results themselves. 
Let me know if you have any other questions!
