### ISSUE TITLE
Error when setting up container

### ISSUE THREAD

**Issue by febert** [avisingh599/reward-learning-rl#13]
Hi,

when running
```
export MJKEY="$(cat ~/.mujoco/mjkey.txt)" \
    && docker-compose \
        -f ./docker/docker-compose.dev.cpu.yml \
        up \
        -d \
        --force-recreate
```
I'm getting the error:

```
  File "/usr/lib/python2.7/dist-packages/compose/service.py", line 13, in <module>
    from docker.utils import LogConfig
ImportError: cannot import name LogConfig
```
How can this be fixed?

Thanks!

**Comment by avisingh599** [comment]
Hmm, I have not seen this error before, do you have a longer version of the trace? 

Also, is your `nvidia-docker` and `docker-compose` relatively recent (say not more than few months old)? 

@hartikainen Any ideas?

**Comment by avisingh599** [comment]
Also, I would suggest using the gpu version of the `.yml` file, i.e. `./docker/docker-compose.dev.gpu.yml`, since the CPU version is quite slow.

**Comment by febert** [comment]
I think the problem is that I didn't install docker compose correctly. I'll try reinstalling it.

**Comment by febert** [comment]
I fixed it by reinstalling docker-compose according to this:
https://docs.docker.com/compose/install/

**Comment by febert** [comment]
I fixed it by reinstalling docker-compose according to this:
https://docs.docker.com/compose/install/

**Comment by avisingh599** [comment]
Great!
