### ISSUE TITLE
Handling reset when training on real robot

### ISSUE THREAD

**Issue by seivazi** [avisingh599/reward-learning-rl#16]
Hi,

how did you handle resetting the environment on the real robot? For example, in the pushing case, is there someone in attendance who gets prompted to reset the cup on environment resets, or does that work entirely without manual reset like in the arena environments (e.g. when it has reached the goal, or an irrecoverable position).

**Comment by avisingh599** [comment]
Hi, 

We indeed have a person in the loop for performing the resets. This is a big bottleneck for scaling robotic learning to harder tasks (since they take more time to learn), and we will soon be releasing a paper that takes steps towards enabling reset-free learning in the real world. Stay tuned!
