### ISSUE TITLE
Workflow recommendation for end to end learning 

### ISSUE THREAD

**Issue by seivazi** [avisingh599/reward-learning-rl#17]
Hi,
Could you share with us some insights into how you approach the end to end learning development workflow?

Specifically, how do you deal with long iteration times for changes (few hours)?
Is there some deployment infrastructure (other than Ray, Docker, and git) in your group?
For example, do you try out one by one or do you submit a batch of changes and somehow a software reports it for you later on.

Cheers,
Shahram

**Comment by avisingh599** [comment]
We usually submit a batch of changes and then re-run everything. The long running times are indeed problematic, which is why the public version of the code is not updated very frequently.
