### ISSUE TITLE
Docker installation not detect Mujoco key

### ISSUE THREAD

**Issue by tunglm2203** [avisingh599/reward-learning-rl#9]
Hi,
Thank you for provide source code, I'm trying to install your framework with docker image, I `ran` command:
`export MJKEY="$(cat ~/.mujoco/mjkey.txt)" && docker-compose -f ./docker/docker-compose.dev.cpu.yml up -d --force-recreate`

But when I go into container, and run command:
`softlearning run_example_local examples.classifier_rl --n_goal_examples 10 --task=Image48SawyerDoorPullHookEnv-v0  --algorithm VICERAQ --num-samples 1 --n_epochs 300 --active_query_frequency 10`

I face the error:

`WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

WARNING: Logging before flag parsing goes to stderr.
I0603 12:03:40.040023 140002190292736 acceleratesupport.py:13] OpenGL_accelerate module loaded
I0603 12:03:40.055296 140002190292736 arraydatatype.py:270] Using accelerated ArrayDatatype
I0603 12:03:40.331384 140002190292736 __init__.py:34] MuJoCo library version is: 200
Warning: robosuite package not found. Run `pip install robosuite` to use robosuite environments.
I0603 12:03:40.355057 140002190292736 __init__.py:333] Registering multiworld mujoco gym environments
F0603 12:03:41.536112 140002190292736 core.py:90] Invalid activation key
Aborted (core dumped)
`
I have tried to import another gym environment (Hopper-v2, FetchReach-v1, etc.) but it notifies "Invalid activation key". I think the docker image not recognize key. Is this problem caused by docker?

**Comment by avisingh599** [comment]
Is your key stored in `~/.mujoco/mjkey.txt` on your system? Are you sure that it's a valid activation key (i.e. you can build mujoco environments outside docker)?

**Comment by tunglm2203** [comment]
@avisingh599 I already have key in `~/.mujoco/mjkey.txt`, I can run Mujoco outside docker normally.

**Comment by tunglm2203** [comment]
I figure out problem, Mujoco needs an institutional license to get rid of hardware-locking mechanism, so it can work with Docker. Personal Student license is hardware-locked.

**Comment by avisingh599** [comment]
Glad you figured it out!
